#version: "3.9"

services:
  app:
    container_name: django_app
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    stdin_open: true
    tty: true

  lint:
    build:
      context: .
    command: sh -c "flake8"
    volumes:
      - ./app:/appp    